SwipeUp "test"
wait 3
SwipeUp "HowToPlaySwipe"
wait 3
SwipeUp "SwipeImage1"
wait 3
SwipeUp "SwipeImage2"
wait 3
SwipeUp "SwipeImage4"
wait 3

if ImageFound (Image:"mypagebtn2", WaitFor:10)
	tap FoundImageLocation()
	Log "テスト勉強","マイページ(2回目)", true
else
	Log "テスト勉強","マイページ(2回目)", false
end if
wait 5
CaptureScreen (Name: "マイページ(2回目)")
wait 3

Tap (Image:"MainMenu" , WaitFor:5)
wait 5
Tap (Image:"PrepareTest", WaitFor:5)
wait 10
